# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\file_downloading.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    global file_name,file_type,file_size  
    file_name = ""  
    file_type = ""
    file_size =""
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(754, 79)
        Form.setMinimumSize(QtCore.QSize(754, 79))
        Form.setMaximumSize(QtCore.QSize(754, 79))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(3, 9, 3, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setMinimumSize(QtCore.QSize(77, 20))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_38.setStyleSheet("QLabel {\n"
"font: 63 12pt \"Open Sans Semibold\";\n"
"    color:rgb(0, 44, 65);\n"
"}")
        self.label_38.setScaledContents(True)
        self.label_38.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_31.addWidget(self.label_38)
        spacerItem = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem)
        self.label_39 = QtWidgets.QLabel(Form)
        self.label_39.setMinimumSize(QtCore.QSize(53, 20))
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_39.setStyleSheet("QLabel {\n"
"    color:rgb(0, 0, 0);\n"
"font: 63 12pt \"Open Sans Semibold\";\n"
"}")
        self.label_39.setScaledContents(True)
        self.label_39.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_31.addWidget(self.label_39)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem1)
        self.progressBar_6 = QtWidgets.QProgressBar(Form)
        self.progressBar_6.setMinimumSize(QtCore.QSize(593, 20))
        self.progressBar_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progressBar_6.setAutoFillBackground(False)
        self.progressBar_6.setStyleSheet("QProgressBar\n"
"{\n"
"    border: solid grey;\n"
"    border-radius: 10px;\n"
"    background: rgb(225, 225, 225);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 87 8pt \"Arial Black\";\n"
"}\n"
"\n"
"QProgressBar::chunk \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(10, 161, 93, 255), stop:1 rgba(0, 44, 65, 255));\n"
"    border-radius: 10px;\n"
"}")
        self.progressBar_6.setProperty("value", 20)
        self.progressBar_6.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_6.setTextVisible(True)
        self.progressBar_6.setInvertedAppearance(False)
        self.progressBar_6.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_6.setObjectName("progressBar_6")
        self.horizontalLayout_31.addWidget(self.progressBar_6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_40 = QtWidgets.QLabel(Form)
        self.label_40.setEnabled(True)
        self.label_40.setMinimumSize(QtCore.QSize(68, 20))
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_40.setStyleSheet("QLabel {\n"
"font: 63 12pt \"Open Sans Semibold\";\n"
"    color:rgb(0, 44, 65);\n"
"}")
        self.label_40.setScaledContents(True)
        self.label_40.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_33.addWidget(self.label_40)
        spacerItem2 = QtWidgets.QSpacerItem(4, 8, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem2)
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_41.setStyleSheet("QLabel {\n"
"    color:rgb(0, 0, 0);\n"
"        font: 63 12pt \"Open Sans Semibold\";\n"
"\n"
"}")
        self.label_41.setScaledContents(True)
        self.label_41.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_33.addWidget(self.label_41)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_33)
        spacerItem3 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem3)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setMinimumSize(QtCore.QSize(63, 20))
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_42.setStyleSheet("QLabel {\n"
"font: 63 12pt \"Open Sans Semibold\";\n"
"    color:rgb(0, 44, 65);\n"
"}")
        self.label_42.setScaledContents(True)
        self.label_42.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_34.addWidget(self.label_42)
        spacerItem4 = QtWidgets.QSpacerItem(4, 8, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem4)
        self.label_43 = QtWidgets.QLabel(Form)
        self.label_43.setMinimumSize(QtCore.QSize(52, 20))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_43.setStyleSheet("QLabel {\n"
"    color:rgb(0, 0, 0);\n"
"    font: 63 12pt \"Open Sans Semibold\";\n"
"}")
        self.label_43.setScaledContents(True)
        self.label_43.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_34.addWidget(self.label_43)
        spacerItem5 = QtWidgets.QSpacerItem(40, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem5)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_34)
        self.verticalLayout_12.addLayout(self.horizontalLayout_32)
        self.gridLayout.addLayout(self.verticalLayout_12, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_38.setText(_translate("Form", "File name:"))
        self.label_39.setText(_translate("Form", file_name))
        self.progressBar_6.setFormat(_translate("Form", "%p%"))
        self.label_40.setText(_translate("Form", "File type:"))
        self.label_41.setText(_translate("Form", file_type))
        self.label_42.setText(_translate("Form", "File size:"))
        self.label_43.setText(_translate("Form", file_size))
